Metrics/AbcSize:
  Max: 42
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 25
Style/Documentation:
  Enabled: false
